hyperparameter_best = dict(future_length = 1, past_omni_length = 120,
                                omni_resolution = 1, nmax = 20,lag = 30,
                                learning_rate = 5e-03,batch_size = 3500,
                                l2reg=1e-3,epochs = 1000, dropout_prob=0.3,n_hidden=8,
                                loss='MAE',model='NeuralRNNWiemer',
                                is_logging_enabled = True, category="train_with_weights")
                                # learning_rate originally 1e-5
md = {'NeuralRNNWiemer_HidddenSuperMAG':NeuralRNNWiemer_HidddenSuperMAG,
        'NeuralRNNWiemer':NeuralRNNWiemer}
hyperparameter_defaults = hyperparameter_best
yearlist = np.arange(2013, 2015)

future_length: 1
past_omni_length: 120
omni_resolution: 1
nmax: 20
lag: 30
learning_rate: 5e-03
batch_size: 3500
l2reg: 1e-3
epochs: 1000
dropout_prob: 0.3
n_hidden: 8
loss: "MAE"
model: 'NeuralRNNWiemer'
is_logging_enabled: True
category: 
