future_length: 1

past_omni_length: 120

omni_resolution: 1

nmax: 20

learning_rate: 0.005

batch_size: 100

l2reg: 0.001

epochs: 1000

dropout_prob: 0.3

n_hidden: 8

loss: "MAE"

model: 'NeuralRNNWiemer'

is_logging_enabled: false

yearlist_begin: 2013

yearlist_end: 2014

wandb_run_name: "Experiment"

preprocessed_data_path: "./preprocessed_data_base"

extra_input_features: []

station_regularization: false

weighted_regression: true