# sweep_config.yaml
method: random
metric:
  name: val_rmse
  goal: minimize
parameters:
  epochs:
    value: 50
  batch_size:
    values: [128, 256, 512]
  lr:
    values: [0.01, 0.001, 0.0001, 0.00001]
  weight_decay:
    values: [0.0, 0.01, 0.001, 0.00001]
  dropout_rate:
    values: [0.2, 0.3, 0.4, 0.5]