# Number of timesteps in input data's time history
past_omni_length: 120

# Measurement cadence in minutes of the input dataset
omni_resolution: 1

# Maximum spherical harmonics order
nmax: 20

# Learning rate for training
learning_rate: 0.005

# Batch size for training
batch_size: 3500

#L2 regularization coefficient
l2reg: 0.001

# Maximum number of epochs
epochs: 1000

# Number of dataloader workers
num_workers: 0

# Number of GPU devices
num_devices: 1

# Dropout probability for the model
dropout_prob: 0.3

# Number of hidden units in the model
n_hidden: 8

# Loss function
loss: "MAE"

# Model architecture
model: 'NeuralRNNWiemer'

# Flag to enable logging 
is_logging_enabled: false

# Start limit of the years
yearlist_begin: 2013

# End limit of the years(This year is not included)
yearlist_end: 2014

# Checkpoint folder name and experiment name in wandb
wandb_run_name: "experiment"

# Path to the preprocessed data
preprocessed_data_path: "./processed_data_stn_reg"

# Input Geomagnetic Indices. Can be a subset of ["SME", "SML", "SMU", "SMR"]
extra_input_features: []

# Flag to enable station regularization
station_regularization: true

# Station Regularization Dampening Factor
stn_reg_dmp: 0.3

# Flag to enable weighted regression for imbalance correction
weighted_regression: false

# The weight associated with the loss function for station regularization
# Used only when both weighted regression and station regularization are enabled
station_regularization_weight: 0.5

# The weight associated with the loss function for imbalanced regression correction
# Used only when both weighted regression and station regularization are enabled
imbalanced_regression_weight: 0.5